/**
 * Shared INVARIANT configuration — flows from CLI init → config file → agent → edge sensor.
 *
 * invariant.config.json is the single source of truth for project-level settings.
 * Generated by `npx @santh/invariant init`, read by agent and edge sensor.
 * Committed to version control (no secrets — keys are in env vars / CF Secrets).
 */

import type { SignalProductCategory } from './crypto/types.js'

// ── Config Schema ───────────────────────────────────────────────

export interface InvariantConfig {
    /** Schema version for forwards compat */
    v: 1

    /** Product category — one question at init, drives collective intelligence segmentation */
    category: SignalProductCategory

    /** Detected framework (express, next, django, etc.) */
    framework: string

    /** Defense mode */
    mode: 'monitor' | 'enforce' | 'off'

    /** Application type */
    appType: 'web' | 'api' | 'saas' | 'internal'

    /** Data classification */
    dataClassification: 'pii' | 'payment' | 'health' | 'none'

    /** Compliance requirements */
    compliance: string[]

    /** Database driver if detected */
    database?: string

    /** Custom plugin paths to load */
    plugins?: string[]

    /** Signal upload settings */
    signals?: {
        /** Signal ingest URL (Santh central) */
        ingestUrl?: string
        /** Batch size before flush */
        batchSize?: number
        /** Sensor token for authentication */
        sensorToken?: string
    }

    /** Block thresholds per severity (override defaults) */
    thresholds?: {
        critical?: number
        high?: number
        medium?: number
        low?: number
    }
}

// ── Defaults ────────────────────────────────────────────────────

export const DEFAULT_CONFIG: InvariantConfig = {
    v: 1,
    category: 'saas',
    framework: 'unknown',
    mode: 'monitor',
    appType: 'web',
    dataClassification: 'none',
    compliance: [],
}

// ── Validation ──────────────────────────────────────────────────

const VALID_CATEGORIES: readonly string[] = [
    'saas', 'api', 'ecommerce', 'fintech', 'healthcare',
    'content', 'devtools', 'gaming', 'education', 'government', 'other',
] as const

const VALID_MODES = ['monitor', 'enforce', 'off'] as const
const VALID_APP_TYPES = ['web', 'api', 'saas', 'internal'] as const
const VALID_DATA_TYPES = ['pii', 'payment', 'health', 'none'] as const

export function isValidCategory(value: string): value is SignalProductCategory {
    return VALID_CATEGORIES.includes(value)
}

export function validateConfig(raw: unknown): InvariantConfig {
    if (!raw || typeof raw !== 'object') {
        throw new ConfigError('Config must be a non-null object')
    }

    const obj = raw as Record<string, unknown>

    // Schema version
    if (obj.v !== undefined && obj.v !== 1) {
        throw new ConfigError(`Unsupported config version: ${obj.v}`)
    }

    const config: InvariantConfig = { ...DEFAULT_CONFIG }

    // Category
    if (typeof obj.category === 'string') {
        if (!isValidCategory(obj.category)) {
            throw new ConfigError(`Invalid category: ${obj.category}. Valid: ${VALID_CATEGORIES.join(', ')}`)
        }
        config.category = obj.category
    }

    // Framework
    if (typeof obj.framework === 'string') {
        config.framework = obj.framework
    }

    // Mode
    if (typeof obj.mode === 'string') {
        if (!(VALID_MODES as readonly string[]).includes(obj.mode)) {
            throw new ConfigError(`Invalid mode: ${obj.mode}. Valid: ${VALID_MODES.join(', ')}`)
        }
        config.mode = obj.mode as InvariantConfig['mode']
    }

    // App type
    if (typeof obj.appType === 'string') {
        if (!(VALID_APP_TYPES as readonly string[]).includes(obj.appType)) {
            throw new ConfigError(`Invalid appType: ${obj.appType}. Valid: ${VALID_APP_TYPES.join(', ')}`)
        }
        config.appType = obj.appType as InvariantConfig['appType']
    }

    // Data classification
    if (typeof obj.dataClassification === 'string') {
        if (!(VALID_DATA_TYPES as readonly string[]).includes(obj.dataClassification)) {
            throw new ConfigError(`Invalid dataClassification: ${obj.dataClassification}`)
        }
        config.dataClassification = obj.dataClassification as InvariantConfig['dataClassification']
    }

    // Compliance
    if (Array.isArray(obj.compliance)) {
        config.compliance = obj.compliance.filter((c): c is string => typeof c === 'string')
    }

    // Database
    if (typeof obj.database === 'string') {
        config.database = obj.database
    }

    // Plugins
    if (Array.isArray(obj.plugins)) {
        config.plugins = obj.plugins.filter((p): p is string => typeof p === 'string')
    }

    // Signals
    if (obj.signals && typeof obj.signals === 'object') {
        const s = obj.signals as Record<string, unknown>
        config.signals = {}
        if (typeof s.ingestUrl === 'string') config.signals.ingestUrl = s.ingestUrl
        if (typeof s.batchSize === 'number') config.signals.batchSize = s.batchSize
        if (typeof s.sensorToken === 'string') config.signals.sensorToken = s.sensorToken
    }

    // Thresholds
    if (obj.thresholds && typeof obj.thresholds === 'object') {
        const t = obj.thresholds as Record<string, unknown>
        config.thresholds = {}
        if (typeof t.critical === 'number') config.thresholds.critical = t.critical
        if (typeof t.high === 'number') config.thresholds.high = t.high
        if (typeof t.medium === 'number') config.thresholds.medium = t.medium
        if (typeof t.low === 'number') config.thresholds.low = t.low
    }

    return config
}

export class ConfigError extends Error {
    constructor(message: string) {
        super(`[InvariantConfig] ${message}`)
        this.name = 'ConfigError'
    }
}
