/**
 * @santh/invariant-engine — Defense Validation
 *
 * Self-testing module that validates the invariant defense patterns
 * catch ALL generated variants. This proves:
 *   1. The defense pattern is correct (no false negatives)
 *   2. Novel variants are caught (not just known signatures)
 *   3. The defense hasn't regressed after changes
 *
 * The fundamental invariant:
 *   For every invariant class C:
 *     For every variant V generated by C.generateVariants():
 *       C.detect(V) MUST return true
 *
 *   If this fails, the defense has a gap — variants exist
 *   that express the invariant property but evade detection.
 */

import { InvariantEngine, type InvariantClass, type InvariantMatch } from './invariant-engine.js'

// ── Validation Types ─────────────────────────────────────────────

export interface ValidationResult {
    /** Invariant class being validated */
    class: InvariantClass
    /** Number of variants generated */
    variantsGenerated: number
    /** Number of variants detected */
    variantsDetected: number
    /** Whether all variants were detected */
    passed: boolean
    /** Variants that evaded detection (gaps!) */
    evasions: string[]
    /** Average confidence across detected variants */
    avgConfidence: number
    /** Minimum confidence across detected variants */
    minConfidence: number
    /** Duration of validation (ms) */
    durationMs: number
}

export interface FullValidationReport {
    /** Total invariant classes tested */
    totalClasses: number
    /** Number of classes that passed */
    classesPassed: number
    /** Number of classes that failed */
    classesFailed: number
    /** Total variants tested */
    totalVariants: number
    /** Total evasions found (defense gaps) */
    totalEvasions: number
    /** Pass rate */
    passRate: number
    /** Per-class results */
    results: ValidationResult[]
    /** Total validation duration (ms) */
    durationMs: number
    /** Timestamp */
    timestamp: string
}

// ── False Positive Validation ────────────────────────────────────

/**
 * Benign inputs that should NEVER trigger detection.
 * False positives are as bad as false negatives — they break
 * the application and erode trust.
 */
const BENIGN_INPUTS = [
    // Normal text
    'Hello, world!',
    'The quick brown fox jumps over the lazy dog.',
    'User requested password reset at 2:30 PM.',

    // Normal URLs
    '/api/users?page=1&limit=20',
    '/products/category/electronics?sort=price',
    '/dashboard/analytics?from=2024-01-01&to=2024-12-31',

    // Normal form data
    'name=John+Doe&email=john@example.com&message=Hello',
    'search=modern+web+development+best+practices',

    // Code-like content that isn't an attack
    'SELECT is a reserved word in many languages.',
    'The table was set for dinner.',
    'Use the UNION keyword to combine queries in documentation.',
    'The script tag is used in HTML for JavaScript.',

    // Normal email addresses
    'contact@company.com',
    'user+tag@domain.org',

    // JSON payloads
    '{"name":"test","email":"user@example.com","count":42}',
    '{"items":[1,2,3],"total":6}',

    // Normal file paths
    '/var/log/app.log',
    '/home/user/documents/report.pdf',
    'C:\\Users\\Documents\\file.txt',

    // Numbers and IDs
    '550e8400-e29b-41d4-a716-446655440000',
    '1234567890',
    'tok_1234567890abcdef',
]

// ── Validator ────────────────────────────────────────────────────

export class DefenseValidator {
    private engine: InvariantEngine

    constructor() {
        this.engine = new InvariantEngine()
    }

    /**
     * Validate a single invariant class.
     * Generates N variants and confirms each is detected.
     */
    validateClass(cls: InvariantClass, variantCount = 10): ValidationResult {
        const start = performance.now()
        const variants = this.engine.generateVariants(cls, variantCount)
        const evasions: string[] = []
        const confidences: number[] = []

        for (const variant of variants) {
            const matches = this.engine.detect(variant, [])
            const classMatch = matches.find(m => m.class === cls)

            if (!classMatch) {
                evasions.push(variant)
            } else {
                confidences.push(classMatch.confidence)
            }
        }

        const avgConfidence = confidences.length > 0
            ? confidences.reduce((s, c) => s + c, 0) / confidences.length
            : 0
        const minConfidence = confidences.length > 0
            ? Math.min(...confidences)
            : 0

        return {
            class: cls,
            variantsGenerated: variants.length,
            variantsDetected: variants.length - evasions.length,
            passed: evasions.length === 0,
            evasions,
            avgConfidence,
            minConfidence,
            durationMs: Math.round(performance.now() - start),
        }
    }

    /**
     * Validate ALL invariant classes.
     * This is the full self-test that should run in CI.
     */
    validateAll(variantCount = 10): FullValidationReport {
        const start = performance.now()
        const classes = this.engine.classes
        const results: ValidationResult[] = []

        for (const cls of classes) {
            results.push(this.validateClass(cls, variantCount))
        }

        const passed = results.filter(r => r.passed).length
        const totalVariants = results.reduce((s, r) => s + r.variantsGenerated, 0)
        const totalEvasions = results.reduce((s, r) => s + r.evasions.length, 0)

        return {
            totalClasses: classes.length,
            classesPassed: passed,
            classesFailed: classes.length - passed,
            totalVariants,
            totalEvasions,
            passRate: classes.length > 0 ? passed / classes.length : 1,
            results,
            durationMs: Math.round(performance.now() - start),
            timestamp: new Date().toISOString(),
        }
    }

    /**
     * Validate false positive resistance.
     * Ensures benign inputs are NOT flagged as attacks.
     */
    validateFalsePositives(additionalInputs: string[] = []): {
        totalInputs: number
        falsePositives: number
        falsePositiveRate: number
        flagged: Array<{ input: string; matches: InvariantMatch[] }>
    } {
        const inputs = [...BENIGN_INPUTS, ...additionalInputs]
        const flagged: Array<{ input: string; matches: InvariantMatch[] }> = []

        for (const input of inputs) {
            const matches = this.engine.detect(input, [])
            if (matches.length > 0) {
                flagged.push({ input, matches })
            }
        }

        return {
            totalInputs: inputs.length,
            falsePositives: flagged.length,
            falsePositiveRate: inputs.length > 0 ? flagged.length / inputs.length : 0,
            flagged,
        }
    }

    /**
     * Run a cross-class confusion test.
     * Ensures that variants of class A are not ONLY detected as class B.
     * Some cross-detection is expected (e.g., SQLi + XSS in the same payload)
     * but the PRIMARY detection should be correct.
     */
    validateCrossClass(variantCount = 5): {
        totalTests: number
        confusions: number
        details: Array<{ variant: string; expectedClass: InvariantClass; detectedClasses: InvariantClass[] }>
    } {
        const classes = this.engine.classes
        const details: Array<{
            variant: string
            expectedClass: InvariantClass
            detectedClasses: InvariantClass[]
        }> = []

        for (const cls of classes) {
            const variants = this.engine.generateVariants(cls, variantCount)
            for (const variant of variants) {
                const matches = this.engine.detect(variant, [])
                const detectedClasses = matches.map(m => m.class)

                // The expected class should be present in the detections
                if (!detectedClasses.includes(cls)) {
                    details.push({
                        variant: variant.slice(0, 100),
                        expectedClass: cls,
                        detectedClasses,
                    })
                }
            }
        }

        return {
            totalTests: classes.length * variantCount,
            confusions: details.length,
            details,
        }
    }
}
