use crate::mitre::MitreTactic;
use crate::types::{AttackCategory, InvariantClass};

/// This registry centralizes metadata for all `InvariantClass` variants.
///
/// LAW 4 CONTRACT: Adding a new `InvariantClass` requires ONLY 4 touches:
/// 1. Add variant to enum in `types.rs`
/// 2. Add one `ClassMetadata` entry here in `class_registry.rs`
/// 3. Create one evaluator file
/// 4. Add one entry to `EVALUATORS` in `evaluators/mod.rs`
pub struct ClassMetadata {
    pub class: InvariantClass,
    pub attack_category: AttackCategory,
    pub severity_weight: f64,
    pub mitre_technique: &'static str,
    pub mitre_tactic: MitreTactic,
    pub compliance_tags: &'static [&'static str],
    pub description: &'static str,
}

pub const ALL_CLASSES: &[InvariantClass] = &[
    InvariantClass::SqlStringTermination,
    InvariantClass::SqlTautology,
    InvariantClass::SqlUnionExtraction,
    InvariantClass::SqlStackedExecution,
    InvariantClass::SqlTimeOracle,
    InvariantClass::SqlErrorOracle,
    InvariantClass::SqlCommentTruncation,
    InvariantClass::XssTagInjection,
    InvariantClass::XssAttributeEscape,
    InvariantClass::XssEventHandler,
    InvariantClass::XssProtocolHandler,
    InvariantClass::XssTemplateExpression,
    InvariantClass::PathDotdotEscape,
    InvariantClass::PathNullTerminate,
    InvariantClass::PathEncodingBypass,
    InvariantClass::PathNormalizationBypass,
    InvariantClass::CmdSeparator,
    InvariantClass::CmdSubstitution,
    InvariantClass::CmdArgumentInjection,
    InvariantClass::SsrfInternalReach,
    InvariantClass::SsrfCloudMetadata,
    InvariantClass::SsrfProtocolSmuggle,
    InvariantClass::DeserJavaGadget,
    InvariantClass::DeserPhpObject,
    InvariantClass::DeserPythonPickle,
    InvariantClass::AuthNoneAlgorithm,
    InvariantClass::AuthHeaderSpoof,
    InvariantClass::CorsOriginAbuse,
    InvariantClass::ProtoPollution,
    InvariantClass::ProtoPollutionGadget,
    InvariantClass::LogJndiLookup,
    InvariantClass::SstiJinjaTwig,
    InvariantClass::SstiElExpression,
    InvariantClass::NosqlOperatorInjection,
    InvariantClass::NosqlJsInjection,
    InvariantClass::LdapFilterInjection,
    InvariantClass::XxeEntityExpansion,
    InvariantClass::XmlInjection,
    InvariantClass::CrlfHeaderInjection,
    InvariantClass::CrlfLogInjection,
    InvariantClass::GraphqlIntrospection,
    InvariantClass::GraphqlBatchAbuse,
    InvariantClass::OpenRedirectBypass,
    InvariantClass::MassAssignment,
    InvariantClass::RegexDos,
    InvariantClass::HttpSmuggleClTe,
    InvariantClass::HttpSmuggleH2,
    InvariantClass::HttpSmuggleChunkExt,
    InvariantClass::HttpSmuggleZeroCl,
    InvariantClass::HttpSmuggleExpect,
    InvariantClass::JsonSqlBypass,
    InvariantClass::DependencyConfusion,
    InvariantClass::PostinstallInjection,
    InvariantClass::EnvExfiltration,
    InvariantClass::LlmPromptInjection,
    InvariantClass::LlmDataExfiltration,
    InvariantClass::LlmJailbreak,
    InvariantClass::WsInjection,
    InvariantClass::WsHijack,
    InvariantClass::JwtKidInjection,
    InvariantClass::JwtJwkEmbedding,
    InvariantClass::JwtConfusion,
    InvariantClass::CachePoisoning,
    InvariantClass::CacheDeception,
    InvariantClass::BolaIdor,
    InvariantClass::ApiMassEnum,
    InvariantClass::OastInteraction,
];

pub static ALL_CLASS_METADATA: &[ClassMetadata] = &[
    ClassMetadata {
        class: InvariantClass::SqlStringTermination,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "String termination bypasses input validation to inject SQL",
    },
    ClassMetadata {
        class: InvariantClass::SqlTautology,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "Boolean-based blind SQLi exploits public-facing database interfaces",
    },
    ClassMetadata {
        class: InvariantClass::SqlUnionExtraction,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.95,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "UNION-based extraction exfiltrates database contents",
    },
    ClassMetadata {
        class: InvariantClass::SqlStackedExecution,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.95,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "Stacked queries enable arbitrary command execution",
    },
    ClassMetadata {
        class: InvariantClass::SqlTimeOracle,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "Time-based blind SQLi uses timing as a side channel",
    },
    ClassMetadata {
        class: InvariantClass::SqlErrorOracle,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "Error-based SQLi uses error messages as data exfiltration channel",
    },
    ClassMetadata {
        class: InvariantClass::SqlCommentTruncation,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.70,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "Comment truncation bypasses authorization logic",
    },
    ClassMetadata {
        class: InvariantClass::XssTagInjection,
        attack_category: AttackCategory::Xss,
        severity_weight: 0.85,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-79",
        ],
        description: "Script tag injection enables drive-by compromise and client execution",
    },
    ClassMetadata {
        class: InvariantClass::XssAttributeEscape,
        attack_category: AttackCategory::Xss,
        severity_weight: 0.70,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-79",
        ],
        description: "Attribute escape breaks out of HTML attribute context",
    },
    ClassMetadata {
        class: InvariantClass::XssEventHandler,
        attack_category: AttackCategory::Xss,
        severity_weight: 0.70,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-79",
        ],
        description: "Event handler XSS executes when user interacts with injected element",
    },
    ClassMetadata {
        class: InvariantClass::XssProtocolHandler,
        attack_category: AttackCategory::Xss,
        severity_weight: 0.70,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-79",
        ],
        description: "javascript: protocol handler executes in page context",
    },
    ClassMetadata {
        class: InvariantClass::XssTemplateExpression,
        attack_category: AttackCategory::Xss,
        severity_weight: 0.70,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-79",
        ],
        description: "Template expression injection can escalate to RCE via SSTI",
    },
    ClassMetadata {
        class: InvariantClass::PathDotdotEscape,
        attack_category: AttackCategory::PathTraversal,
        severity_weight: 0.85,
        mitre_technique: "T1083",
        mitre_tactic: MitreTactic::Discovery,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Directory traversal reads arbitrary files from the filesystem",
    },
    ClassMetadata {
        class: InvariantClass::PathNullTerminate,
        attack_category: AttackCategory::PathTraversal,
        severity_weight: 0.70,
        mitre_technique: "T1083",
        mitre_tactic: MitreTactic::Discovery,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Null byte truncates filename extensions to bypass filters",
    },
    ClassMetadata {
        class: InvariantClass::PathEncodingBypass,
        attack_category: AttackCategory::PathTraversal,
        severity_weight: 0.85,
        mitre_technique: "T1083",
        mitre_tactic: MitreTactic::Discovery,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Encoding bypass evades path traversal filters",
    },
    ClassMetadata {
        class: InvariantClass::PathNormalizationBypass,
        attack_category: AttackCategory::PathTraversal,
        severity_weight: 0.70,
        mitre_technique: "T1083",
        mitre_tactic: MitreTactic::Discovery,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Path normalization differences between parser and filesystem",
    },
    ClassMetadata {
        class: InvariantClass::CmdSeparator,
        attack_category: AttackCategory::Cmdi,
        severity_weight: 0.95,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Shell metacharacter injection enables arbitrary command execution",
    },
    ClassMetadata {
        class: InvariantClass::CmdSubstitution,
        attack_category: AttackCategory::Cmdi,
        severity_weight: 0.95,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Subshell substitution $(cmd) executes in host context",
    },
    ClassMetadata {
        class: InvariantClass::CmdArgumentInjection,
        attack_category: AttackCategory::Cmdi,
        severity_weight: 0.85,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Argument injection manipulates command-line tool behavior",
    },
    ClassMetadata {
        class: InvariantClass::SsrfInternalReach,
        attack_category: AttackCategory::Ssrf,
        severity_weight: 0.85,
        mitre_technique: "T1210",
        mitre_tactic: MitreTactic::LateralMovement,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "HIPAA-164.312-e1",
            "NIST-SC-7",
            "A10:2021",
            "CWE-20",
        ],
        description: "SSRF accesses internal network resources from the application",
    },
    ClassMetadata {
        class: InvariantClass::SsrfCloudMetadata,
        attack_category: AttackCategory::Ssrf,
        severity_weight: 0.95,
        mitre_technique: "T1552",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "HIPAA-164.312-e1",
            "NIST-SC-7",
            "A10:2021",
            "CWE-20",
        ],
        description: "Cloud metadata SSRF extracts IAM credentials from instance metadata service",
    },
    ClassMetadata {
        class: InvariantClass::SsrfProtocolSmuggle,
        attack_category: AttackCategory::Ssrf,
        severity_weight: 0.85,
        mitre_technique: "T1071",
        mitre_tactic: MitreTactic::CommandAndControl,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "HIPAA-164.312-e1",
            "NIST-SC-7",
            "A10:2021",
            "CWE-20",
        ],
        description: "Protocol smuggling accesses non-HTTP internal services",
    },
    ClassMetadata {
        class: InvariantClass::DeserJavaGadget,
        attack_category: AttackCategory::Deser,
        severity_weight: 0.95,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Java deserialization gadget chains enable RCE",
    },
    ClassMetadata {
        class: InvariantClass::DeserPhpObject,
        attack_category: AttackCategory::Deser,
        severity_weight: 0.85,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "PHP object injection via unserialize()",
    },
    ClassMetadata {
        class: InvariantClass::DeserPythonPickle,
        attack_category: AttackCategory::Deser,
        severity_weight: 0.95,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Python pickle deserialization executes arbitrary __reduce__",
    },
    ClassMetadata {
        class: InvariantClass::AuthNoneAlgorithm,
        attack_category: AttackCategory::Auth,
        severity_weight: 0.85,
        mitre_technique: "T1078",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "SOC2-CC6.1",
            "A02:2021",
            "API2:2023",
            "CWE-20",
        ],
        description: "Generic detection.",
    },
    ClassMetadata {
        class: InvariantClass::AuthHeaderSpoof,
        attack_category: AttackCategory::Auth,
        severity_weight: 0.85,
        mitre_technique: "T1078",
        mitre_tactic: MitreTactic::PrivilegeEscalation,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Forwarding header spoofing bypasses IP-based access controls",
    },
    ClassMetadata {
        class: InvariantClass::CorsOriginAbuse,
        attack_category: AttackCategory::Auth,
        severity_weight: 0.70,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "CORS misconfiguration allows cross-origin credential theft",
    },
    ClassMetadata {
        class: InvariantClass::ProtoPollution,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1068",
        mitre_tactic: MitreTactic::PrivilegeEscalation,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Prototype pollution modifies Object.prototype to escalate privileges",
    },
    ClassMetadata {
        class: InvariantClass::ProtoPollutionGadget,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1068",
        mitre_tactic: MitreTactic::PrivilegeEscalation,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Prototype pollution gadget chains escalate to RCE",
    },
    ClassMetadata {
        class: InvariantClass::LogJndiLookup,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A09:2021",
            "CWE-20",
        ],
        description: "JNDI lookup enables remote class loading and RCE",
    },
    ClassMetadata {
        class: InvariantClass::SstiJinjaTwig,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Jinja2/Twig SSTI enables arbitrary Python/PHP code execution",
    },
    ClassMetadata {
        class: InvariantClass::SstiElExpression,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1059",
        mitre_tactic: MitreTactic::Execution,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Expression Language injection enables arbitrary Java execution",
    },
    ClassMetadata {
        class: InvariantClass::NosqlOperatorInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "MongoDB operator injection bypasses authentication and exfiltrates data",
    },
    ClassMetadata {
        class: InvariantClass::NosqlJsInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Server-side JavaScript injection in NoSQL databases",
    },
    ClassMetadata {
        class: InvariantClass::LdapFilterInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "LDAP filter injection bypasses authentication",
    },
    ClassMetadata {
        class: InvariantClass::XxeEntityExpansion,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "XML external entity reads local files and performs SSRF",
    },
    ClassMetadata {
        class: InvariantClass::XmlInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "XML injection modifies document structure to bypass access controls",
    },
    ClassMetadata {
        class: InvariantClass::CrlfHeaderInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "CRLF injection manipulates HTTP response headers",
    },
    ClassMetadata {
        class: InvariantClass::CrlfLogInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1070",
        mitre_tactic: MitreTactic::DefenseEvasion,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A09:2021",
            "CWE-20",
        ],
        description: "Log injection forges log entries to cover tracks",
    },
    ClassMetadata {
        class: InvariantClass::GraphqlIntrospection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1046",
        mitre_tactic: MitreTactic::Discovery,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "GraphQL introspection reveals entire API schema",
    },
    ClassMetadata {
        class: InvariantClass::GraphqlBatchAbuse,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1499",
        mitre_tactic: MitreTactic::Impact,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "GraphQL batch/nested queries cause denial of service",
    },
    ClassMetadata {
        class: InvariantClass::OpenRedirectBypass,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1189",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Open redirect chains with phishing for credential theft",
    },
    ClassMetadata {
        class: InvariantClass::MassAssignment,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1068",
        mitre_tactic: MitreTactic::PrivilegeEscalation,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Mass assignment escalates privileges by setting admin fields",
    },
    ClassMetadata {
        class: InvariantClass::RegexDos,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1499",
        mitre_tactic: MitreTactic::Impact,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Catastrophic regex backtracking causes CPU exhaustion",
    },
    ClassMetadata {
        class: InvariantClass::HttpSmuggleClTe,
        attack_category: AttackCategory::Smuggling,
        severity_weight: 0.85,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "CL.TE desync enables request smuggling through proxy chains",
    },
    ClassMetadata {
        class: InvariantClass::HttpSmuggleH2,
        attack_category: AttackCategory::Smuggling,
        severity_weight: 0.85,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "H2.CL downgrade attack exploits HTTP/2 to HTTP/1.1 conversion",
    },
    ClassMetadata {
        class: InvariantClass::HttpSmuggleChunkExt,
        attack_category: AttackCategory::Smuggling,
        severity_weight: 0.70,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Chunk extension smuggling exploits HTTP/1.1 chunked encoding",
    },
    ClassMetadata {
        class: InvariantClass::HttpSmuggleZeroCl,
        attack_category: AttackCategory::Smuggling,
        severity_weight: 0.70,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Zero Content-Length smuggling exploits edge cases in body parsing",
    },
    ClassMetadata {
        class: InvariantClass::HttpSmuggleExpect,
        attack_category: AttackCategory::Smuggling,
        severity_weight: 0.70,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Expect header smuggling exploits 100-Continue handling",
    },
    ClassMetadata {
        class: InvariantClass::JsonSqlBypass,
        attack_category: AttackCategory::Sqli,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "A03:2021",
            "CWE-89",
        ],
        description: "JSON-wrapped SQL payloads bypass WAF signature matching",
    },
    ClassMetadata {
        class: InvariantClass::DependencyConfusion,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1195",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "PCI-6.3.2",
            "CWE-20",
        ],
        description: "Dependency confusion substitutes public package for private one",
    },
    ClassMetadata {
        class: InvariantClass::PostinstallInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1195.002",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "PCI-6.3.2",
            "CWE-20",
        ],
        description: "Package postinstall scripts execute arbitrary code during install",
    },
    ClassMetadata {
        class: InvariantClass::EnvExfiltration,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1552",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Environment variable exfiltration steals credentials",
    },
    ClassMetadata {
        class: InvariantClass::LlmPromptInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Prompt injection overrides LLM system instructions",
    },
    ClassMetadata {
        class: InvariantClass::LlmDataExfiltration,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1005",
        mitre_tactic: MitreTactic::Collection,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "LLM data exfiltration extracts training data or system prompts",
    },
    ClassMetadata {
        class: InvariantClass::LlmJailbreak,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1553",
        mitre_tactic: MitreTactic::DefenseEvasion,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "LLM jailbreak bypasses safety controls",
    },
    ClassMetadata {
        class: InvariantClass::WsInjection,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "WebSocket message injection exploits bidirectional channel",
    },
    ClassMetadata {
        class: InvariantClass::WsHijack,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.85,
        mitre_technique: "T1185",
        mitre_tactic: MitreTactic::Collection,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "WebSocket hijacking takes over established connections",
    },
    ClassMetadata {
        class: InvariantClass::JwtKidInjection,
        attack_category: AttackCategory::Auth,
        severity_weight: 0.85,
        mitre_technique: "T1550",
        mitre_tactic: MitreTactic::DefenseEvasion,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "JWT kid parameter injection enables path traversal or SQLi in key lookup",
    },
    ClassMetadata {
        class: InvariantClass::JwtJwkEmbedding,
        attack_category: AttackCategory::Auth,
        severity_weight: 0.85,
        mitre_technique: "T1550",
        mitre_tactic: MitreTactic::DefenseEvasion,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Embedded JWK in JWT header provides attacker-controlled signing key",
    },
    ClassMetadata {
        class: InvariantClass::JwtConfusion,
        attack_category: AttackCategory::Auth,
        severity_weight: 0.85,
        mitre_technique: "T1550",
        mitre_tactic: MitreTactic::DefenseEvasion,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Algorithm confusion attack uses public key as HMAC secret",
    },
    ClassMetadata {
        class: InvariantClass::CachePoisoning,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1557",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Cache poisoning serves malicious content via unkeyed headers",
    },
    ClassMetadata {
        class: InvariantClass::CacheDeception,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1539",
        mitre_tactic: MitreTactic::CredentialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Cache deception tricks CDN into caching sensitive responses",
    },
    ClassMetadata {
        class: InvariantClass::BolaIdor,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1078",
        mitre_tactic: MitreTactic::PrivilegeEscalation,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "SOC2-CC6.1",
            "CWE-20",
        ],
        description: "Broken object-level authorization allows accessing other users resources",
    },
    ClassMetadata {
        class: InvariantClass::ApiMassEnum,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.70,
        mitre_technique: "T1119",
        mitre_tactic: MitreTactic::Collection,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Mass API enumeration extracts all records via sequential ID",
    },
    ClassMetadata {
        class: InvariantClass::OastInteraction,
        attack_category: AttackCategory::Injection,
        severity_weight: 0.95,
        mitre_technique: "T1190",
        mitre_tactic: MitreTactic::InitialAccess,
        compliance_tags: &[
            "PCI-6.2.4",
            "PCI-6.2.3.1",
            "SOC2-CC7.1",
            "SOC2-CC7.2",
            "GDPR-Art.32",
            "HIPAA-164.308",
            "HIPAA-164.312",
            "NIST-SI-10",
            "NIST-RA-5",
            "ISO-8.28",
            "ISO-8.8",
            "CWE-20",
        ],
        description: "Generic detection.",
    },
];

pub fn get_metadata(class: InvariantClass) -> &'static ClassMetadata {
    ALL_CLASS_METADATA
        .iter()
        .find(|m| m.class == class)
        .unwrap_or_else(|| panic!("Missing metadata for {class:?}"))
}

pub fn attack_category_for(class: InvariantClass) -> AttackCategory {
    get_metadata(class).attack_category
}

pub fn severity_for(class: InvariantClass) -> f64 {
    get_metadata(class).severity_weight
}

pub fn mitre_for(class: InvariantClass) -> (&'static str, MitreTactic) {
    let m = get_metadata(class);
    (m.mitre_technique, m.mitre_tactic)
}

pub fn compliance_for(class: InvariantClass) -> &'static [&'static str] {
    get_metadata(class).compliance_tags
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn test_all_classes_mapped() {
        assert_eq!(ALL_CLASS_METADATA.len(), ALL_CLASSES.len());
        for class in ALL_CLASSES {
            assert!(ALL_CLASS_METADATA.iter().any(|m| m.class == *class));
        }
    }

    #[test]
    fn test_no_duplicates() {
        let mut seen = HashSet::new();
        for m in ALL_CLASS_METADATA {
            assert!(seen.insert(m.class), "Duplicate entry for {:?}", m.class);
        }
    }

    #[test]
    fn test_severity_bounds() {
        for m in ALL_CLASS_METADATA {
            assert!(m.severity_weight >= 0.0 && m.severity_weight <= 1.0);
        }
    }

    #[test]
    fn test_mitre_not_empty() {
        for m in ALL_CLASS_METADATA {
            assert!(!m.mitre_technique.is_empty());
        }
    }
}
