export const CONFIDENCE_MIN = 0
export const CONFIDENCE_MAX = 0.99
export const CONFIDENCE_DEFAULT_FALLBACK = 0.5
export const REGISTRY_DEFAULT_BASE_CONFIDENCE = 0.85
export const REGISTRY_FALSE_POSITIVE_MULTIPLIER = 0.5
export const REGISTRY_SHORT_INPUT_MULTIPLIER = 0.7
export const REGISTRY_CONVERGENT_BOOST = 0.10

export const SEVERITY_THRESHOLD_CRITICAL = 0.45
export const SEVERITY_THRESHOLD_HIGH = 0.65
export const SEVERITY_THRESHOLD_MEDIUM = 0.80
export const SEVERITY_THRESHOLD_LOW = 0.92

export const COMPLETE_COMPOSITION_THRESHOLD = 0.90
export const COMPLETE_SKIP_PRIORITY_FLOOR = 0.05
export const DEFAULT_BLOCK_THRESHOLD = 0.75
export const BOOST_CONVERGENT = 0.05

export const L1_ONLY_ATTENUATION = 0.82
export const CONTEXT_BOOST_PRIMARY = 0.10
export const CONTEXT_BOOST_SECONDARY = 0.04
export const CONTEXT_ATTENUATION_UNRELATED = 0.85

export const SOURCE_REPUTATION_MIN = 0.6
export const SOURCE_REPUTATION_SCALE = 0.4
export const SOURCE_REPUTATION_BOOST = 0.05
export const CREDENTIAL_STUFFING_PATH_BOOST = 0.08
export const CREDENTIAL_STUFFING_POST_BOOST = 0.04
export const CREDENTIAL_STUFFING_CONTENTTYPE_BOOST = 0.03
export const CREDENTIAL_STUFFING_GET_PENALTY = 0.90
export const TEMPLATE_PATH_BOOST = 0.07
export const TEMPLATE_PATH_PENALTY = 0.05
export const TEMPLATE_TYPE_BOOST = 0.03
export const TEMPLATE_IMAGE_PENALTY = 0.92

export const CVE_ACTIVE_EXPLOIT_BOOST = 0.05

export const PROOF_STEP_BASE = 0.40
export const PROOF_STEP_INCREMENT = 0.20
export const PROOF_STEP_COMPLETENESS_BONUS = 0.05
export const PROOF_STEP_SEMANTIC_BONUS = 0.04
export const PROOF_STEP_MAX = 0.90
export const PROOF_L2_MIN_SCALE = 0.85
export const PROOF_CONFIDENCE_MAX = 0.99
